// Automatically generated by MockGen. DO NOT EDIT!
// Source: goresource/store (interfaces: Store)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Store interface
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *_MockStoreRecorder
}

// Recorder for MockStore (not exported)
type _MockStoreRecorder struct {
	mock *MockStore
}

func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &_MockStoreRecorder{mock}
	return mock
}

func (_m *MockStore) EXPECT() *_MockStoreRecorder {
	return _m.recorder
}

func (_m *MockStore) Close() {
	_m.ctrl.Call(_m, "Close")
}

func (_mr *_MockStoreRecorder) Close() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Close")
}

func (_m *MockStore) CreateEntity(_param0 string, _param1 interface{}, _param2 interface{}) error {
	ret := _m.ctrl.Call(_m, "CreateEntity", _param0, _param1, _param2)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockStoreRecorder) CreateEntity(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CreateEntity", arg0, arg1, arg2)
}

func (_m *MockStore) DeleteEntity(_param0 string, _param1 string) error {
	ret := _m.ctrl.Call(_m, "DeleteEntity", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockStoreRecorder) DeleteEntity(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeleteEntity", arg0, arg1)
}

func (_m *MockStore) GetEntity(_param0 string, _param1 string, _param2 interface{}) error {
	ret := _m.ctrl.Call(_m, "GetEntity", _param0, _param1, _param2)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockStoreRecorder) GetEntity(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetEntity", arg0, arg1, arg2)
}

func (_m *MockStore) ListEntities(_param0 string, _param1 interface{}, _param2 interface{}) error {
	ret := _m.ctrl.Call(_m, "ListEntities", _param0, _param1, _param2)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockStoreRecorder) ListEntities(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ListEntities", arg0, arg1, arg2)
}

func (_m *MockStore) UpdateEntity(_param0 string, _param1 string, _param2 interface{}, _param3 interface{}) error {
	ret := _m.ctrl.Call(_m, "UpdateEntity", _param0, _param1, _param2, _param3)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockStoreRecorder) UpdateEntity(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "UpdateEntity", arg0, arg1, arg2, arg3)
}
